### ISSUE TITLE
the GPU memory usage sometimes spikes unexpectedly

### ISSUE THREAD

**Issue by ak01user** [thewh1teagle/kokoro-onnx#37]
![image](https://github.com/user-attachments/assets/c4cb061a-4423-46e5-af4a-9632f896a4e1)
well done, this project is truly amazing and very user-friendly. I tried using it on a GPU with the CUDAExecutionProvider, but during inference, the GPU memory usage sometimes spikes unexpectedly. Why is that? Gpu is 4090 with 24gb.

**Comment by satvikpendem** [comment]
@ak01user How are you running it on GPU? I have a 3080 and it still looks like it's using the CPU, anything specific I need to do or modify?

**Comment by ak01user** [comment]
hi, you only need to modify the providers parameter, but please make sure you have installed onnxruntime-gpu  @satvikpendem 
`providers = ['CUDAExecutionProvider'] # specific CUDA mode
session = InferenceSession(
            "./data/kokoro-v0_19.onnx", providers=providers
        )
kokoro_instance = Kokoro.from_session(session, "./data/voices.json")`

**Comment by satvikpendem** [comment]
Thanks, got it. Having some issues running CUDA on Windows but I'll try on WSL and see.

**Comment by ak01user** [comment]
I have encapsulated the API using FastAPI. I simulated 100 requests, each generating 8 seconds of audio. It took 136 seconds in CPU mode and 41 seconds on the GPU. My device has an i7-13700KF CPU and an RTX 4090 GPU.

**Comment by satvikpendem** [comment]
I see the issue, `uv` automatically overrides and installs the CPU version (`onnxruntime`) and uses that when you run `uv run hello.py` even if you install the GPU version, because only the CPU version is specified in the kokoro-onnx dependencies. @thewh1teagle is there a way to add a flag to add the GPU version instead?

**Comment by thewh1teagle** [comment]
> I see the issue, `uv` automatically overrides and installs the CPU version (`onnxruntime`) and uses that when you run `uv run hello.py` even if you install the GPU version, because only the CPU version is specified in the kokoro-onnx dependencies.

Good finding! Thanks
You can use pip directly with uv for instance

```console
uv pip uninstall onnxruntime
uv pip install onnxruntime-gpu
```

Then run it. let me know if it still overrides it.
As for long term solution in kokoro-onnx. I thought maybe add option to install kokoro-onnx with `pip install kokoro-onnx[gpu]`
Then it will use onnxruntime-gpu instead. I need to see how feature flags with dependencies works best with `uv`

**Comment by thewh1teagle** [comment]
@satvikpendem 

I released new version with gpu support.
See [examples/with_gpu.py](https://github.com/thewh1teagle/kokoro-onnx/blob/be2fe91f22fb7ef4976cf90220c4e8b26e4d46f5/examples/with_gpu.py)

**Comment by satvikpendem** [comment]
> Then run it. let me know if it still overrides it.

@thewh1teagle Yes uv does still override it because it detects that onnxruntime (non GPU) is in the dependencies list and automatically installs that before running. Only my method seems to work to override the dependency to the GPU version.

**Comment by thewh1teagle** [comment]
> Yes uv does still override it because it detects that onnxruntime (non GPU) is in the dependencies list and automatically installs that before running. Only my method seems to work to override the dependency to the GPU version. For your example, are you doing `uv pip install kokoro-onnx[gpu]` and that works fine on GPU with CUDA?

After the last update, if you install `kokoro-onnx[gpu]` it works?

**Comment by satvikpendem** [comment]
> After the last update, if you install `kokoro-onnx[gpu]` it works?

Still getting the following error, the GPU is not being detected while it is in the raw Python venv instructions I shared above.

```sh
kokoro/.venv/lib/python3.12/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py:115: UserWarning: Specified provider 'CUDAExecutionProvider' is not in available provider names.Available providers: 'AzureExecutionProvider, CPUExecutionProvider'
```

**Comment by ccyrene** [comment]
If both onnxruntime and onnxruntime-gpu are installed, it always defaults to using onnxruntime. You can resolve this by specifying separate versions for CPU and GPU in the pyproject.toml, like so:
```
[project.optional-dependencies]
gpu = [
    "onnxruntime-gpu>=1.20.1"
]
cpu = [
    "onnxruntime>=1.20.1"
]
```
Alternatively, if you don’t want to split the versions, you can set the default dependency to onnxruntime-gpu>=1.20.1. If a GPU isn’t detected, it will fall back to using the CPU, or you can set the provider manually in the source code.

**Comment by thewh1teagle** [comment]
> This is probably the best way as the GPU version of onnxruntime is already a superset of the CPU version, so people don't have to worry about which one to install.

**Comment by thewh1teagle** [comment]
> > Alternatively, if you don’t want to split the versions, you can set the default dependency to onnxruntime-gpu>=1.20.1. If a GPU isn’t detected, it will fall back to using the CPU, or you can set the provider manually in the source code.
> 
> This is probably the best way as the GPU version of onnxruntime is already a superset of the CPU version, so people don't have to worry about which one to install.

I don't think so because the gou wheel is much larger

**Comment by thewh1teagle** [comment]
> [@thewh1teagle](https://github.com/thewh1teagle) If both onnxruntime and onnxruntime-gpu are installed, it always defaults to using onnxruntime. You can resolve this by specifying separate versions for CPU and GPU in the pyproject.toml, like so:
> 
> ```
> [project.optional-dependencies]
> gpu = [
>     "onnxruntime-gpu>=1.20.1"
> ]
> cpu = [
>     "onnxruntime>=1.20.1"
> ]
> ```
> 
> Alternatively, if you don’t want to split the versions, you can set the default dependency to onnxruntime-gpu>=1.20.1. If a GPU isn’t detected, it will fall back to using the CPU, or you can set the provider manually in the source code.

Can we install cpu by default unless kokoro-onnx[gpu] specified with pip?
